export type ConservationStatus = "LC" | "NT" | "VU" | "EN" | "CR" | "NE" | "DD";

export interface SpeciesPlaceholder {
  id: string;
  slug: string;
  scientificName: string;
  author: string;
  year: number;
  commonNameEs: string;
  commonNameEn: string;
  family: string;
  subfamily: string;
  genus: string;
  order: string;
  catalogNum: string;
  conservationStatus: ConservationStatus;
  geographicOrigin: string;
  presenceInMexico: boolean;
  mexicoStates: string[];
  image: string;
  gallery: { src: string; caption: string; credit: string }[];
  aspectRatio: string; // e.g. "3/4", "4/5", "1/1"
  tags: string[];
  foodPlants: string[];
  habitat: string;
  behavior: string;
  description: string;
  females: string;
  males: string;
  nymphs: string;
  eggs: string;
  breeding: string;
  references: string[];
}

export const STATUS_META: Record<
  ConservationStatus,
  { label: string; color: string; bg: string }
> = {
  LC: { label: "Preocupación menor", color: "text-lichen", bg: "bg-lichen/10" },
  NT: { label: "Casi amenazado",    color: "text-gold",   bg: "bg-gold/10"   },
  VU: { label: "Vulnerable",        color: "text-amber",  bg: "bg-amber/10"  },
  EN: { label: "En peligro",        color: "text-red-400",bg: "bg-red-400/10"},
  CR: { label: "En peligro crítico",color: "text-red-600",bg: "bg-red-600/10"},
  NE: { label: "No evaluado",       color: "text-text3",  bg: "bg-border"    },
  DD: { label: "Datos insuficientes",color:"text-text3",  bg: "bg-border"    },
};

export const FAMILIES = [
  "Todas las familias",
  "Diapheromeridae",
  "Bacillidae",
  "Phasmatidae",
  "Phylliidae",
  "Heteropterygidae",
  "Pseudophasmatidae",
  "Lonchodidae",
];

export const PLACEHOLDER_SPECIES: SpeciesPlaceholder[] = [
  {
    id: "1",
    slug: "carausius-morosus",
    scientificName: "Carausius morosus",
    author: "Sinéty, 1901",
    year: 1901,
    commonNameEs: "Insecto palo indio",
    commonNameEn: "Indian stick insect",
    family: "Diapheromeridae",
    subfamily: "Lonchodinae",
    genus: "Carausius",
    order: "Phasmatodea",
    catalogNum: "CAT-001",
    conservationStatus: "LC",
    geographicOrigin: "India · Sri Lanka",
    presenceInMexico: false,
    mexicoStates: [],
    image: "https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800&q=85&fit=crop&crop=center",
    aspectRatio: "3/4",
    tags: ["exótica", "cultivo", "partenogénesis"],
    gallery: [
      { src: "https://images.unsplash.com/photo-1502082553048-f009c37129b9?w=900&q=85", caption: "Hembra adulta en reposo diurno", credit: "© Placeholder" },
      { src: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=900&q=85", caption: "Detalle de extremidades anteriores", credit: "© Placeholder" },
      { src: "https://images.unsplash.com/photo-1448375240586-882707db888b?w=900&q=85", caption: "Huevos depositados en sustrato", credit: "© Placeholder" },
    ],
    foodPlants: ["Lilas (Ligustrum)", "Hiedra (Hedera)", "Roble (Quercus)", "Frambuesa (Rubus)"],
    habitat: "Bosques húmedos subtropicales y selvas tropicales de media montaña entre 500 y 1,800 m s.n.m. Prefiere vegetación densa con alta humedad relativa.",
    behavior: "Especie de hábitos nocturnos que permanece inmóvil durante el día simulando una rama. Es la especie más cultivada en terrariofilia por su robustez y reproducción partenogenética.",
    description: "Carausius morosus es el insecto palo más conocido y cultivado en el mundo. Las hembras son de color verde parduzco con las patas anteriores teñidas de rojo en la cara ventral. Los machos son extremadamente raros en estado silvestre; la reproducción es casi exclusivamente partenogenética. Su tamaño oscila entre 70 y 95 mm en hembras adultas.",
    females: "Hembras robustas de 70–95 mm, coloración verde con reflejos pardos. Patas anteriores con coloración rojiza en la cara ventral. Tegumentos levemente rugosos. Abdomen voluminoso. Antenas cortas en relación al cuerpo.",
    males: "Machos extremadamente escasos en poblaciones silvestres. Cuando aparecen, miden 55–65 mm y presentan coloración más uniforme. La población en cultivo es casi exclusivamente femenina.",
    nymphs: "Ninfas eclosionan de color verde brillante uniforme. Pasan por 6 estadios ninfales antes de la muda imaginal. A partir del tercer estadio comienzan a manifestar los tonos pardos característicos de los adultos.",
    eggs: "Huevos de forma ovoide, 2.5–3 mm de longitud, coloración marrón grisácea con cápsula opercular diferenciada. Se depositan individualmente en el sustrato. Incubación a 23–25 °C: 3–4 meses.",
    breeding: "Especie ideal para principiantes. Temperatura óptima 22–26 °C. Humedad relativa 60–70%. Alimentar con Ligustrum fresco renovado cada 3 días. Los huevos pueden incubarse sobre vermiculita húmeda a temperatura ambiente.",
    references: [
      "Sinéty, R. de (1901). Recherches biologiques et morphologiques sur les Phasmes. Ann. Sci. nat. Zool., 13: 1–270.",
      "Brock, P.D. (1999). The Amazing World of Stick and Leaf Insects. Amateur Entomologist's Society, Feltham.",
      "Ragge, D.R. (1955). The Wing-Venation of the Orthoptera Saltatoria. BMNH, London.",
    ],
  },
  {
    id: "2",
    slug: "bacillus-rossius",
    scientificName: "Bacillus rossius",
    author: "Rossi, 1788",
    year: 1788,
    commonNameEs: "Insecto palo mediterráneo",
    commonNameEn: "Mediterranean stick insect",
    family: "Bacillidae",
    subfamily: "Bacillinae",
    genus: "Bacillus",
    order: "Phasmatodea",
    catalogNum: "CAT-002",
    conservationStatus: "LC",
    geographicOrigin: "Europa mediterránea",
    presenceInMexico: false,
    mexicoStates: [],
    image: "https://images.unsplash.com/photo-1448375240586-882707db888b?w=800&q=85&fit=crop&crop=center",
    aspectRatio: "4/5",
    tags: ["exótica", "mediterránea", "dimorfismo sexual"],
    gallery: [
      { src: "https://images.unsplash.com/photo-1509316785289-025f5b846b35?w=900&q=85", caption: "Hembra adulta en Cistus", credit: "© Placeholder" },
      { src: "https://images.unsplash.com/photo-1516026672322-bc52d61a55d5?w=900&q=85", caption: "Macho adulto mostrando alas vestigiales", credit: "© Placeholder" },
    ],
    foodPlants: ["Jara (Cistus)", "Romero (Rosmarinus)", "Frambuesa (Rubus)", "Roble (Quercus)"],
    habitat: "Matorrales mediterráneos, maquis y garrigas desde el nivel del mar hasta los 1,500 m. Ampliamente distribuido en el litoral mediterráneo europeo y norte de África.",
    behavior: "Activo principalmente al anochecer. A diferencia de C. morosus, existe reproducción sexual con machos bien representados en las poblaciones. Los adultos pueden ser verdes, pardos o grises según el microhábitat.",
    description: "Bacillus rossius es el fásmido más común de la región mediterránea. Presenta marcado dimorfismo sexual: las hembras son grandes y robustas mientras que los machos son delgados y tienen vestigios de alas. La especie exhibe variación cromática adaptativa notable.",
    females: "70–95 mm, robustas, coloración variable: verde, parda o grisácea. Sin alas funcionales. Cuerpo cilíndrico con tegumentos ligeramente granulados.",
    males: "55–75 mm, delgados, frecuentemente de coloración más oscura. Presentan alas anteriores (tegminas) y posteriores vestigiales aunque no funcionales para el vuelo.",
    nymphs: "Ninfas de color verde brillante, muy ágiles. 6 estadios ninfales. La diferenciación sexual es visible a partir del tercer estadio.",
    eggs: "Huevos con ornamentación superficial característica, 3–3.5 mm, coloración castaño oscuro. Requieren periodo de hibernación a 10–15 °C durante 2–3 meses.",
    breeding: "Temperatura de cría 22–28 °C en verano, 15–18 °C en invierno. Los huevos necesitan diapausa fría para eclosionar. Alimentar con Rubus o Quercus.",
    references: [
      "Rossi, P. (1788). Fauna Etrusca. vol. 2. Masi, Liburni.",
      "Scali, V., Passamonti, M. & Marescalchi, O. (2003). Chromosomes of Bacillus rossius: standard karyotype and NOR mapping. Caryologia 56: 1–9.",
    ],
  },
  {
    id: "3",
    slug: "eurycantha-calcarata",
    scientificName: "Eurycantha calcarata",
    author: "Lucas, 1869",
    year: 1869,
    commonNameEs: "Insecto palo espinoso gigante",
    commonNameEn: "Giant spiny stick insect",
    family: "Phasmatidae",
    subfamily: "Eurycanthinae",
    genus: "Eurycantha",
    order: "Phasmatodea",
    catalogNum: "CAT-003",
    conservationStatus: "LC",
    geographicOrigin: "Nueva Guinea",
    presenceInMexico: false,
    mexicoStates: [],
    image: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800&q=85&fit=crop&crop=center",
    aspectRatio: "1/1",
    tags: ["exótica", "terrícola", "espinosa"],
    gallery: [
      { src: "https://images.unsplash.com/photo-1502082553048-f009c37129b9?w=900&q=85", caption: "Macho adulto mostrando espinas femorales", credit: "© Placeholder" },
      { src: "https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=900&q=85", caption: "Pareja en terrario naturalista", credit: "© Placeholder" },
    ],
    foodPlants: ["Eukalyptus (Eucalyptus)", "Frambuesa (Rubus)", "Roble (Quercus)", "Hiedra (Hedera)"],
    habitat: "Selvas tropicales húmedas de baja altitud en Nueva Guinea. Especie terrícola que se refugia bajo corteza y entre raíces. Prefiere ambientes con alta humedad y suelo húmedo.",
    behavior: "Especie terrestres y arborícola. Los machos son agresivos y utilizan las espinas femorales como mecanismo de defensa. Activos principalmente de noche. Viven en grupos en condiciones de cautiverio.",
    description: "Una de las especies más robustas y espectaculares del orden. Los machos adultos presentan dos grandes espinas en los fémures posteriores usadas en combates intraespecíficos. Las hembras son de mayor tamaño pero carecen de espinas prominentes.",
    females: "120–155 mm, las más grandes de la especie. Coloración marrón oscuro con patrón moteado. Sin las espinas pronunciadas de los machos pero con cuerpo más voluminoso.",
    males: "100–130 mm, con dos espinas características en los fémures del último par de patas. Abdomen más estrecho que las hembras. Muy activos y territoriales.",
    nymphs: "Ninfas de color verde brillante que oscurece progresivamente. Muy activas desde el primer estadio. Las espinas de los machos aparecen a partir del cuarto estadio.",
    eggs: "Grandes, 5–6 mm, forma elipsoidal irregular, coloración castaño rojizo. Se entierran en el sustrato. Incubación lenta: 4–6 meses a 25–27 °C.",
    breeding: "Requiere caja de cría con sustrato profundo (10 cm mínimo) para oviposición. Temperatura 24–28 °C. Humedad alta: 70–80%. Pulverizar diariamente.",
    references: [
      "Lucas, H. (1869). Animaux nouveaux ou rares. Arthropodes. Casterman, Paris.",
      "Brock, P.D. & Hasenpusch, J. (2009). The Complete Field Guide to Stick and Leaf Insects of Australia. CSIRO Publishing.",
    ],
  },
  {
    id: "4",
    slug: "extatosoma-tiaratum",
    scientificName: "Extatosoma tiaratum",
    author: "Macleay, 1826",
    year: 1826,
    commonNameEs: "Insecto palo australiano",
    commonNameEn: "Macleay's spectre",
    family: "Phasmatidae",
    subfamily: "Extatosomatinae",
    genus: "Extatosoma",
    order: "Phasmatodea",
    catalogNum: "CAT-004",
    conservationStatus: "LC",
    geographicOrigin: "Australia",
    presenceInMexico: false,
    mexicoStates: [],
    image: "https://images.unsplash.com/photo-1502082553048-f009c37129b9?w=800&q=85&fit=crop&crop=center",
    aspectRatio: "3/4",
    tags: ["exótica", "mimetismo mirmecomorfo", "alas funcionales"],
    gallery: [
      { src: "https://images.unsplash.com/photo-1516026672322-bc52d61a55d5?w=900&q=85", caption: "Hembra adulta con abdomen enrollado", credit: "© Placeholder" },
      { src: "https://images.unsplash.com/photo-1448375240586-882707db888b?w=900&q=85", caption: "Ninfa primer estadio imitando hormiga", credit: "© Placeholder" },
    ],
    foodPlants: ["Eucalyptus spp.", "Acacia spp.", "Guava (Psidium)", "Roble (Quercus)"],
    habitat: "Bosques esclerófilos de eucaliptos en el este y norte de Australia, desde el nivel del mar hasta los 1,500 m. Asociada a zonas con colonias de hormigas del género Leptomyrmex.",
    behavior: "Las ninfas recién eclosionadas imitan con fidelidad asombrosa a las hormigas del género Leptomyrmex para evitar depredación. Las hembras adultas enroscan el abdomen sobre el cuerpo en postura defensiva. Los machos son voladores capaces.",
    description: "Extatosoma tiaratum es famoso por el extraordinario mimetismo mirmecomorfo de sus ninfas en primer estadio. Los huevos poseen una estructura grasa llamada elaiosoma que atrae a las hormigas para transportarlos a sus nidos, facilitando la dispersión.",
    females: "100–200 mm, una de las más grandes de Australia. Coloración verde o parda con el abdomen frecuentemente enroscado sobre el dorso. Alas anteriores reducidas, no funcionales.",
    males: "60–110 mm, mucho más esbeltos. Alas completamente desarrolladas y funcionales. Capaces de vuelo sostenido. Coloración más uniforme que las hembras.",
    nymphs: "En primer estadio: coloración roja con abdomen negro, imitando perfectamente a las hormigas Leptomyrmex. A partir del segundo estadio pierden el mimetismo y adoptan coloración críptica verde.",
    eggs: "Largos (5–6 mm), forma de semilla, con elaiosoma (estructura grasa) que atrae a las hormigas. Coloración grisácea. Incubación: 4–6 meses.",
    breeding: "Terrario de malla de al menos 40×40×60 cm. Temperatura 22–28 °C. Humedad relativa 60–70%. Los machos vuelan activamente y pueden escapar si el terrario no está bien sellado.",
    references: [
      "Macleay, W.S. (1826). Annulosa Javanica. Kingsbury, Parbury & Allen, London.",
      "Hughes, L. & Westoby, M. (1992). Capitula on stick insect eggs and elaiosomes on seeds: convergent adaptations for burial by ants. Funct. Ecol. 6: 642–648.",
      "Bedford, G.O. (1978). Biology and ecology of the Phasmatodea. Annu. Rev. Entomol. 23: 125–149.",
    ],
  },
  {
    id: "5",
    slug: "heteropteryx-dilatata",
    scientificName: "Heteropteryx dilatata",
    author: "Parkinson, 1798",
    year: 1798,
    commonNameEs: "Ninfa de la jungla malaya",
    commonNameEn: "Malayan jungle nymph",
    family: "Heteropterygidae",
    subfamily: "Dataminae",
    genus: "Heteropteryx",
    order: "Phasmatodea",
    catalogNum: "CAT-005",
    conservationStatus: "LC",
    geographicOrigin: "Malasia · Borneo",
    presenceInMexico: false,
    mexicoStates: [],
    image: "https://images.unsplash.com/photo-1516026672322-bc52d61a55d5?w=800&q=85&fit=crop&crop=center",
    aspectRatio: "4/5",
    tags: ["exótica", "la más pesada", "colores vivos"],
    gallery: [
      { src: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=900&q=85", caption: "Hembra adulta verde con espinas amarillas", credit: "© Placeholder" },
      { src: "https://images.unsplash.com/photo-1509316785289-025f5b846b35?w=900&q=85", caption: "Macho adulto marrón en postura defensiva", credit: "© Placeholder" },
    ],
    foodPlants: ["Guayaba (Psidium guajava)", "Frambuesa (Rubus)", "Roble (Quercus)", "Mango (Mangifera)"],
    habitat: "Selvas tropicales húmedas de las tierras bajas de Malasia y Borneo hasta 1,000 m. Se oculta entre la hojarasca y vegetación densa del sotobosque durante el día.",
    behavior: "Las hembras producen un sonido al frotar sus alas cuando son perturbadas (estridulación). Especie muy longeva: las hembras pueden vivir más de 18 meses en cautiverio. Dimorfismo sexual extremo en color y forma.",
    description: "Heteropteryx dilatata ostenta el récord del insecto palo más pesado del mundo. Las hembras adultas pueden pesar hasta 65 g. El dimorfismo sexual es extremo: hembras verdes, grandes y espinosas; machos marrones, delgados y ágiles. Es una de las especies más impresionantes para terrariofilia.",
    females: "150–200 mm, hasta 65 g de peso. Verde brillante con espinas amarillas distribuidas por todo el cuerpo. Alas anteriores reducidas, verdes. Las más grandes del orden Phasmatodea en masa corporal.",
    males: "90–120 mm, delgados. Coloración marrón rojiza uniforme. Alas bien desarrolladas aunque rara vez vuelan. Mucho más ágiles que las hembras.",
    nymphs: "Ninfas inicialmente verdes brillantes, indistinguibles por sexo hasta el quinto estadio. Espinas visibles desde el segundo estadio. Ciclo ninfal muy largo: 9–12 meses.",
    eggs: "Los más grandes del orden: 10–12 mm, forma de bellota. Incubación extremadamente lenta: 9–18 meses. Requieren sustrato húmedo profundo y temperatura de 26–28 °C.",
    breeding: "Especie exigente. Requiere terrario grande (mínimo 60×60×120 cm para hembra). Alta humedad (70–80%). Alimentación con hojas de guayaba o frambuesa. La larga incubación de huevos requiere paciencia.",
    references: [
      "Parkinson, S. (1798). A Journal of a Voyage to the South Seas. Richardson & Co., London.",
      "Brock, P.D. (2001). Stick Insects of Britain, Europe and the Mediterranean. Fitzgerald, London.",
    ],
  },
  {
    id: "6",
    slug: "phyllium-giganteum",
    scientificName: "Phyllium giganteum",
    author: "Hausleithner, 1984",
    year: 1984,
    commonNameEs: "Insecto hoja gigante de Malasia",
    commonNameEn: "Giant Malaysian leaf insect",
    family: "Phylliidae",
    subfamily: "Phylliidae",
    genus: "Phyllium",
    order: "Phasmatodea",
    catalogNum: "CAT-006",
    conservationStatus: "NE",
    geographicOrigin: "Malasia peninsular",
    presenceInMexico: false,
    mexicoStates: [],
    image: "https://images.unsplash.com/photo-1509316785289-025f5b846b35?w=800&q=85&fit=crop&crop=center",
    aspectRatio: "3/4",
    tags: ["exótica", "insecto hoja", "camuflaje extremo"],
    gallery: [
      { src: "https://images.unsplash.com/photo-1502082553048-f009c37129b9?w=900&q=85", caption: "Hembra adulta sobre hoja de guayaba", credit: "© Placeholder" },
      { src: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=900&q=85", caption: "Detalle venación alar imitando hoja", credit: "© Placeholder" },
    ],
    foodPlants: ["Guayaba (Psidium guajava)", "Rambután (Nephelium)", "Mango (Mangifera indica)", "Roble (Quercus)"],
    habitat: "Selvas tropicales húmedas de la península de Malasia y Sumatra. Vive en el dosel y sotobosque de bosques primarios y secundarios maduros.",
    behavior: "El camuflaje de Phyllium giganteum es considerado uno de los más perfectos del reino animal. El insecto imita no solo el color sino la textura, venación, manchas de enfermedad e incluso los bordes irregulares de las hojas. Se mueve mecánicamente imitando el balanceo de una hoja al viento.",
    description: "Phyllium giganteum pertenece a la familia Phylliidae, los llamados insectos hoja. Su cuerpo completamente aplanado y la apariencia de hoja —con venación visible, manchas irregulares y bordes lobulados— constituyen uno de los mimetismos más sofisticados conocidos en la naturaleza.",
    females: "80–100 mm, con el cuerpo completamente aplanado. Las alas anteriores imitan perfectamente una hoja verde con venación detallada. Capaces de vuelo limitado. Bordes del cuerpo lobulados.",
    males: "60–80 mm, más estrechos. Alas completamente desarrolladas con venación alar real. Muy ágiles y voladores activos. Antenas más largas en proporción al cuerpo.",
    nymphs: "Color rojo intenso en primer estadio, cambian a verde en el segundo. La forma de hoja es reconocible desde el primer estadio. 6 estadios ninfales.",
    eggs: "Forma irregular que imita semillas, 5 mm. Coloración marrón oscuro. Incubación: 4–6 meses a 25–27 °C sobre vermiculita húmeda.",
    breeding: "Temperatura 24–28 °C. Humedad alta: 70–80%. Requiere ventilación pero sin corrientes de aire. Alimentar exclusivamente con hojas frescas de guayaba o mango.",
    references: [
      "Hausleithner, B. (1984). Phyllium giganteum sp. nov. Ent. Zeit. 94(4): 41–48.",
      "Wedmann, S., Bradler, S. & Rust, J. (2007). The first fossil leaf insect: 47 million years of specialized cryptic morphology. PNAS 104: 565–569.",
    ],
  },
  {
    id: "7",
    slug: "bacteria-ploiaria",
    scientificName: "Bacteria ploiaria",
    author: "Stoll, 1813",
    year: 1813,
    commonNameEs: "Insecto palo de Veracruz",
    commonNameEn: "Veracruz stick insect",
    family: "Diapheromeridae",
    subfamily: "Diapheromerinae",
    genus: "Bacteria",
    order: "Phasmatodea",
    catalogNum: "CAT-007",
    conservationStatus: "LC",
    geographicOrigin: "México · Centroamérica",
    presenceInMexico: true,
    mexicoStates: ["Veracruz", "Oaxaca", "Chiapas", "Tabasco"],
    image: "https://images.unsplash.com/photo-1560719887-fe3105fa1e55?w=800&q=85&fit=crop&crop=center",
    aspectRatio: "4/5",
    tags: ["nativa", "México", "selva tropical"],
    gallery: [
      { src: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=900&q=85", caption: "Ejemplar de Bacteria ploiaria en Sierra de los Tuxtlas", credit: "© Placeholder" },
    ],
    foodPlants: ["Helecho arbóreo (Cyathea)", "Bromelia spp.", "Rubus spp."],
    habitat: "Selvas húmedas y bosques mesófilos de montaña entre 200 y 1,200 m s.n.m. Registrada principalmente en el sotobosque de selvas altas perennifolias del Golfo de México.",
    behavior: "Especie nocturna. Se mueve lentamente y con movimientos ondulantes que imitan ramas en el viento. Las hembras depositan huevos individualmente en el suelo. Poco documentada en su biología reproductiva.",
    description: "Bacteria ploiaria es una de las especies de fásmidos nativas más representativas del sureste mexicano. Recientemente documentada en la Sierra de los Tuxtlas (Veracruz) en expediciones del equipo de Phasma MX. Su taxonomía ha sido revisada en los últimos años con técnicas moleculares.",
    females: "80–110 mm, verdes o pardas. Cuerpo cilíndrico con tegumentos lisos. Abdomen más robusto que el tórax.",
    males: "65–85 mm. Similares a las hembras en coloración pero más esbeltos. Poco conocidos en campo.",
    nymphs: "Verde brillante uniforme. 6 estadios. La diferenciación sexual aparece en el cuarto estadio.",
    eggs: "Similares al género. Ovoides, 3 mm, castaño claro. Poca información disponible sobre el período de incubación en condiciones naturales.",
    breeding: "Temperatura 22–26 °C. Humedad media. Alimentar con Rubus o helechos nativos.",
    references: [
      "Stoll, C. (1813). Representation des spectres. Sepp, Amsterdam.",
      "Zompro, O. (2004). Revision of the genera of the Areolatae. Goecke & Evers, Keltern.",
    ],
  },
  {
    id: "8",
    slug: "diapheromera-velii",
    scientificName: "Diapheromera velii",
    author: "Walsh, 1864",
    year: 1864,
    commonNameEs: "Insecto palo norteño",
    commonNameEn: "Northern walkingstick",
    family: "Diapheromeridae",
    subfamily: "Diapheromerinae",
    genus: "Diapheromera",
    order: "Phasmatodea",
    catalogNum: "CAT-008",
    conservationStatus: "LC",
    geographicOrigin: "México · Estados Unidos",
    presenceInMexico: true,
    mexicoStates: ["Chihuahua", "Sonora", "Coahuila", "Nuevo León", "Tamaulipas", "San Luis Potosí"],
    image: "https://images.unsplash.com/photo-1510784722466-f2aa240af4cf?w=800&q=85&fit=crop&crop=center",
    aspectRatio: "3/4",
    tags: ["nativa", "México", "bosques templados", "norte"],
    gallery: [
      { src: "https://images.unsplash.com/photo-1448375240586-882707db888b?w=900&q=85", caption: "Adulto sobre encino en Chihuahua", credit: "© Placeholder" },
    ],
    foodPlants: ["Encino (Quercus)", "Nogal (Juglans)", "Sauce (Salix)", "Cerezos silvestres (Prunus)"],
    habitat: "Bosques templados de encino-pino entre 800 y 2,500 m s.n.m. en el norte y noreste de México. También presente en chaparrales y bosques riparios.",
    behavior: "Especie diurna en ciertas condiciones. Capaz de autotomía (desprendimiento voluntario de patas). En años con alta densidad poblacional puede causar defoliación notable en encinos.",
    description: "Diapheromera velii es la especie de fásmido más ampliamente distribuida en el norte de México y los estados del sur de los Estados Unidos. A diferencia de muchas otras, puede alcanzar densidades poblacionales considerables que en ocasiones han sido reportadas como plagas locales menores.",
    females: "75–95 mm. Verdes o pardas. Cuerpo esbelto y cilíndrico. Patas largas proporcionales al cuerpo.",
    males: "65–75 mm. Más delgados. Similares en coloración. Antenas notablemente más largas.",
    nymphs: "Verde brillante, muy crípticas sobre encinos. 6 estadios ninfales. La diferenciación sexual es posible desde el tercer estadio.",
    eggs: "Negros con tapa blanca opercular, 2.5 mm. Dispersados individualmente desde las ramas durante la marcha. Requieren diapausa invernal.",
    breeding: "Requiere temperaturas frías en invierno para eclosión de huevos. Temperatura de cría: 20–24 °C. Alimentar con Quercus o Prunus.",
    references: [
      "Walsh, B.D. (1864). On the phytophagic varieties and phytophagic species, with remarks on the unity of coloration in insects. Proc. Ent. Soc. Philadelphia 3: 403–430.",
    ],
  },
  {
    id: "9",
    slug: "metriophasma-diocles",
    scientificName: "Metriophasma diocles",
    author: "Westwood, 1859",
    year: 1859,
    commonNameEs: "Insecto palo panameño",
    commonNameEn: "Panamanian stick insect",
    family: "Pseudophasmatidae",
    subfamily: "Pseudophasmatinae",
    genus: "Metriophasma",
    order: "Phasmatodea",
    catalogNum: "CAT-009",
    conservationStatus: "NE",
    geographicOrigin: "Centroamérica · Panamá",
    presenceInMexico: true,
    mexicoStates: ["Chiapas"],
    image: "https://images.unsplash.com/photo-1511497584788-876760111969?w=800&q=85&fit=crop&crop=center",
    aspectRatio: "1/1",
    tags: ["nativa", "centroamérica", "selva"],
    gallery: [
      { src: "https://images.unsplash.com/photo-1502082553048-f009c37129b9?w=900&q=85", caption: "Ejemplar en hoja de Heliconia", credit: "© Placeholder" },
    ],
    foodPlants: ["Heliconia spp.", "Plátano (Musa)", "Cafeto (Coffea)", "Rubus spp."],
    habitat: "Selvas tropicales húmedas de tierras bajas y piedemonte centroamericano entre 0 y 800 m s.n.m. Registrada hasta el extremo sur de Chiapas (México).",
    behavior: "Especie exclusivamente nocturna. Durante el día permanece inmóvil sobre ramas con el cuerpo perfectamente alineado a la dirección del soporte. Defensa química mediante secreción de glándulas torácicas.",
    description: "Metriophasma diocles es representativa de la fauna de Centroamérica y su presencia marginal en Chiapas la convierte en una especie de interés biogeográfico para México. La familia Pseudophasmatidae incluye varias especies con capacidad de defensa química activa.",
    females: "90–120 mm. Pardas con patrón listado dorsal. Cuerpo moderadamente robusto. Tegumentos granulados.",
    males: "70–90 mm. Más delgados y con mayor contraste en el patrón de coloración.",
    nymphs: "Verde con una línea dorsal amarilla. Cambian progresivamente a coloración parda. 6 estadios.",
    eggs: "Ovalados, 3.5 mm, castaño rojizo. Incubación: 3–5 meses a 26–28 °C.",
    breeding: "Alta temperatura (25–29 °C) y humedad (70–80%). Alimentar con Heliconia o Musa. Ventilación moderada.",
    references: [
      "Westwood, J.O. (1859). Catalogue of the orthopterous insects in the collection of the British Museum. BMNH, London.",
    ],
  },
  {
    id: "10",
    slug: "agathemera-crassa",
    scientificName: "Agathemera crassa",
    author: "Blanchard, 1851",
    year: 1851,
    commonNameEs: "Palo de Chile",
    commonNameEn: "Chilean stick insect",
    family: "Pseudophasmatidae",
    subfamily: "Agathamerinae",
    genus: "Agathemera",
    order: "Phasmatodea",
    catalogNum: "CAT-010",
    conservationStatus: "VU",
    geographicOrigin: "Chile · Argentina",
    presenceInMexico: false,
    mexicoStates: [],
    image: "https://images.unsplash.com/photo-1518173946687-a4c8892bbd9f?w=800&q=85&fit=crop&crop=center",
    aspectRatio: "4/5",
    tags: ["exótica", "sudamérica", "vulnerable"],
    gallery: [
      { src: "https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=900&q=85", caption: "Hembra adulta en matorral andino", credit: "© Placeholder" },
    ],
    foodPlants: ["Zumaque (Rhus)", "Aromo (Acacia caven)", "Huañil (Proustia)", "Molle (Schinus)"],
    habitat: "Matorrales y estepas arbustivas andinas y preandinas de Chile central y Argentina entre 200 y 1,800 m s.n.m. Asociada a formaciones de Rhus y Schinus.",
    behavior: "Especie robusta y de movimientos lentos. Los adultos pueden emitir un líquido defensivo de olor penetrante cuando son perturbados. Especie terrícola y trepadora.",
    description: "Agathemera crassa pertenece a una familia endémica de Sudamérica con morfología muy diferente a los fásmidos europeos o asiáticos: cuerpo robusto, colores llamativos y aspecto más parecido a un escarabajo que a una rama. Catalogada como Vulnerable por la degradación de su hábitat natural.",
    females: "90–120 mm. Coloración muy variable: verde, amarilla, naranja o rojiza. Tegumentos brillantes. Sin alas.",
    males: "70–90 mm. Más oscuros. Muy poco conocidos en campo.",
    nymphs: "Coloridas, con patrón aposemático. Verde con franjas amarillas y negras en primeros estadios.",
    eggs: "4 mm, con ornamentación superficial rugosa. Castaño oscuro. Incubación: 4–6 meses.",
    breeding: "Temperatura 18–24 °C. Humedad moderada (50–65%). Diapausa fría recomendada para los huevos (12 °C, 2 meses).",
    references: [
      "Blanchard, E. (1851). Catalogue des collections entomologiques. Musée d'Histoire Naturelle, Paris.",
      "Camousseight, A. (2006). Taxonomy of Chilean Agathemera. Rev. Chil. Entomol. 32: 5–42.",
    ],
  },
  {
    id: "11",
    slug: "sipyloidea-sipylus",
    scientificName: "Sipyloidea sipylus",
    author: "Westwood, 1859",
    year: 1859,
    commonNameEs: "Insecto palo de Singapur",
    commonNameEn: "Pink-winged stick insect",
    family: "Diapheromeridae",
    subfamily: "Necrosciinae",
    genus: "Sipyloidea",
    order: "Phasmatodea",
    catalogNum: "CAT-011",
    conservationStatus: "LC",
    geographicOrigin: "Sudeste asiático",
    presenceInMexico: false,
    mexicoStates: [],
    image: "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?w=800&q=85&fit=crop&crop=center",
    aspectRatio: "3/4",
    tags: ["exótica", "alas rosas", "partenogénesis"],
    gallery: [
      { src: "https://images.unsplash.com/photo-1516026672322-bc52d61a55d5?w=900&q=85", caption: "Hembra adulta desplegando alas rosas en vuelo defensivo", credit: "© Placeholder" },
    ],
    foodPlants: ["Hiedra (Hedera)", "Lilas (Ligustrum)", "Eucalyptus spp.", "Frambuesa (Rubus)"],
    habitat: "Selvas tropicales del sudeste asiático: Tailandia, Vietnam, Indonesia, Malasia. También naturalizada en Madagascar.",
    behavior: "Cuando es perturbada despliega repentinamente sus alas posteriores de color rosa brillante, sorprendiendo a posibles depredadores. Reproducción principalmente partenogenética.",
    description: "Sipyloidea sipylus es conocida coloquialmente como el insecto palo de alas rosas. Su estrategia de defensa —el despliegue súbito de llamativas alas posteriores rosas desde un cuerpo perfectamente críptico— es un ejemplo excelente de la teoría del sobresalto (startle display).",
    females: "90–110 mm. Verde uniforme con alas posteriores rosas ocultas en reposo. Ligera rugosidad en tegumentos.",
    males: "70–85 mm. Escasos en cultivo. Más delgados que las hembras.",
    nymphs: "Verdes brillantes, agiles. Sin las alas rosas hasta el estadio adulto. 6 estadios.",
    eggs: "3 mm, pardos, con opérculo. Incubación: 3–4 meses a 25 °C.",
    breeding: "Fácil de criar. Temperatura 22–27 °C. Humedad 60–70%. Muy apropiada para colecciones escolares por su rusticidad.",
    references: [
      "Westwood, J.O. (1859). Catalogue of the orthopterous insects. BMNH, London.",
    ],
  },
  {
    id: "12",
    slug: "ctenomorpha-chronus",
    scientificName: "Ctenomorpha chronus",
    author: "Gray, 1835",
    year: 1835,
    commonNameEs: "Insecto palo gigante de Australia",
    commonNameEn: "Giant Australian stick insect",
    family: "Phasmatidae",
    subfamily: "Phasmatinae",
    genus: "Ctenomorpha",
    order: "Phasmatodea",
    catalogNum: "CAT-012",
    conservationStatus: "LC",
    geographicOrigin: "Australia oriental",
    presenceInMexico: false,
    mexicoStates: [],
    image: "https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=800&q=85&fit=crop&crop=center",
    aspectRatio: "4/5",
    tags: ["exótica", "australia", "gigante"],
    gallery: [
      { src: "https://images.unsplash.com/photo-1502082553048-f009c37129b9?w=900&q=85", caption: "Ejemplar macho adulto sobre eucalipto", credit: "© Placeholder" },
    ],
    foodPlants: ["Eucalyptus spp.", "Acacia spp.", "Leptospermum spp."],
    habitat: "Bosques de eucaliptos de la costa oriental de Australia. Principalmente en el sotobosque húmedo entre 0 y 1,200 m s.n.m.",
    behavior: "Los machos son voladores activos; las hembras son sedentarias. Ciclo de vida largo con múltiples estadios ninfales. Una de las especies más longevas en cautiverio.",
    description: "Ctenomorpha chronus es uno de los fásmidos más grandes de Australia. Los machos poseen alas completamente funcionales y son voladores activos, en contraste con las hembras que permanecen estacionarias. Su cultivo requiere paciencia por la lenta tasa de crecimiento.",
    females: "180–220 mm, de las más largas del continente australiano. Pardo grisáceas con tegumentos rugosos. Sin alas funcionales.",
    males: "100–140 mm. Con alas anteriores (tegminas) cortas y alas posteriores funcionales. Más ágiles y de vida más corta.",
    nymphs: "Verde brillante. 7 estadios ninfales en hembras, 6 en machos. Ciclo muy lento: 10–14 meses hasta adulto.",
    eggs: "Muy grandes: 7–8 mm. Coloración castaño claro con diseño dorsal oscuro. Incubación lenta: 6–9 meses.",
    breeding: "Terrario alto (mínimo 90 cm). Temperatura 22–26 °C. Humedad 60–70%. Alimentar con Eucalyptus o Acacia.",
    references: [
      "Gray, G.R. (1835). Synopsis of the species of insects belonging to the family of Phasmidae. Longman & Co., London.",
      "Brock, P.D. & Hasenpusch, J. (2009). Complete Field Guide to Stick and Leaf Insects of Australia. CSIRO Publishing.",
    ],
  },
];
